In [1]:
import pandas as pd

In [2]:
files = ['../Data/EmploymentDirectVsIndirect/Employment_directVsIndirect2018.csv', 
         '../Data/EmploymentDirectVsIndirect/Employment_directVsIndirect2019.csv', 
         '../Data/EmploymentDirectVsIndirect/Employment_directVsIndirect2020.csv', 
         '../Data/EmploymentDirectVsIndirect/Employment_directVsIndirect2021.csv', 
         '../Data/EmploymentDirectVsIndirect/Employment_directVsIndirect2022.csv', 
         '../Data/EmploymentDirectVsIndirect/Employment_directVsIndirect2023.csv']

In [3]:
dfs = []
for file in files:
    df = pd.read_csv(file)
    year = int(file.split('Employment_directVsIndirect')[1].split('.csv')[0])
    df['Year']= year
    dfs.append(df)

In [4]:
employment_merged_df = pd.concat(dfs, ignore_index=True)

In [5]:
employment_merged_df.to_csv('../employmentdirectindirect.csv', index=False)

In [6]:
employment_merged_df

,Industry,Direct tourism employment,Total industry employment multiplier,Total tourism-related employment,Year
0,Traveler accommodations,"1,555",1.42,"2,211",2018
1,Vacation home rentals,12,1.58,18,2018
2,Food services and drinking places,"1,835",1.18,"2,169",2018
3,Air transportation services,556,2.54,"1,413",2018
4,Rail transportation services,8,2.06,17,2018
...,...,...,...,...,...
157,Industries producing nondurable PCE commoditie...,173,2.45,422,2023
158,Wholesale trade and transportation services,169,1.81,307,2023
159,Gasoline service stations,189,1.24,234,2023
160,"Retail trade services, excluding gasoline serv...",415,1.20,496,2023
161,All other industries,114,1.77,201,2023

employment_merged_df.to_csv('employmentdirectindirect.csv')

In [7]:
employment_merged_df['Direct tourism employment'] = pd.to_numeric(employment_merged_df['Direct tourism employment'].astype(str).str.replace(',', ''), errors='coerce')
employment_merged_df['Total tourism-related employment'] = pd.to_numeric(employment_merged_df['Total tourism-related employment'].astype(str).str.replace(',', ''), errors='coerce')

In [8]:
employment_merged_df['Indirect tourism employment'] = (employment_merged_df['Total tourism-related employment'] - employment_merged_df['Direct tourism employment'])

In [9]:
employment_merged_df.head()

,Industry,Direct tourism employment,Total industry employment multiplier,Total tourism-related employment,Year,Indirect tourism employment
0,Traveler accommodations,1555,1.42,2211,2018,656
1,Vacation home rentals,12,1.58,18,2018,6
2,Food services and drinking places,1835,1.18,2169,2018,334
3,Air transportation services,556,2.54,1413,2018,857
4,Rail transportation services,8,2.06,17,2018,9

In [10]:
data_2018 = employment_merged_df[employment_merged_df['Year'] == 2018]

In [11]:
totals_2018 = data_2018.groupby('Industry')[['Direct tourism employment','Indirect tourism employment','Total tourism-related employment']].sum()
totals_2018.head()

,Direct tourism employment,Indirect tourism employment,Total tourism-related employment
Industry,,,
Air transportation services,556,857,1413
All other industries,97,75,172
All other recreation and entertainment,59,12,71
Automotive equipment rental and leasing,96,92,188
Automotive repair services,49,14,63

In [12]:
total_2018 = data_2018[['Direct tourism employment',  'Indirect tourism employment', 'Total tourism-related employment']].sum()
total_2018

Direct tourism employment           6191
Indirect tourism employment         3380
Total tourism-related employment    9571
dtype: int64

In [13]:
data_2019 = employment_merged_df[employment_merged_df['Year'] == 2019]
totals_2019 = data_2019.groupby('Industry')[['Direct tourism employment','Indirect tourism employment','Total tourism-related employment']].sum()
total_2019= data_2019[['Direct tourism employment',  'Indirect tourism employment', 'Total tourism-related employment']].sum()
total_2019

Direct tourism employment           6392
Indirect tourism employment         3497
Total tourism-related employment    9889
dtype: int64

In [14]:
data_2020 = employment_merged_df[employment_merged_df['Year'] == 2020]
totals_2020 = data_2020.groupby('Industry')[['Direct tourism employment','Indirect tourism employment','Total tourism-related employment']].sum()
total_2020= data_2020[['Direct tourism employment',  'Indirect tourism employment', 'Total tourism-related employment']].sum()
total_2020

Direct tourism employment           3676
Indirect tourism employment         2180
Total tourism-related employment    5856
dtype: int64

In [15]:
data_2021 = employment_merged_df[employment_merged_df['Year'] == 2021]
totals_2021 = data_2021.groupby('Industry')[['Direct tourism employment','Indirect tourism employment','Total tourism-related employment']].sum()
total_2021= data_2021[['Direct tourism employment',  'Indirect tourism employment', 'Total tourism-related employment']].sum()
total_2021

Direct tourism employment           5106
Indirect tourism employment         2760
Total tourism-related employment    7866
dtype: int64

In [16]:
data_2022 = employment_merged_df[employment_merged_df['Year'] == 2022]
totals_2022 = data_2022.groupby('Industry')[['Direct tourism employment','Indirect tourism employment','Total tourism-related employment']].sum()
total_2022= data_2022[['Direct tourism employment',  'Indirect tourism employment', 'Total tourism-related employment']].sum()
total_2022

Direct tourism employment           5840
Indirect tourism employment         3237
Total tourism-related employment    9077
dtype: int64

In [17]:
data_2023 = employment_merged_df[employment_merged_df['Year'] == 2023]
totals_2023 = data_2023.groupby('Industry')[['Direct tourism employment','Indirect tourism employment','Total tourism-related employment']].sum()
total_2023= data_2023[['Direct tourism employment',  'Indirect tourism employment', 'Total tourism-related employment']].sum()
total_2023

Direct tourism employment            6453
Indirect tourism employment          3547
Total tourism-related employment    10000
dtype: int64

In [18]:
industry_employment_2018 = data_2018[['Industry','Direct tourism employment','Indirect tourism employment','Total tourism-related employment']]

In [19]:
industry_employment_2018

,Industry,Direct tourism employment,Indirect tourism employment,Total tourism-related employment
0,Traveler accommodations,1555,656,2211
1,Vacation home rentals,12,6,18
2,Food services and drinking places,1835,334,2169
3,Air transportation services,556,857,1413
4,Rail transportation services,8,9,17
5,Water transportation services,52,118,170
6,Interurban bus transportation,22,12,34
7,Interurban charter bus transportation,22,11,33
8,Urban transit systems and other transportation,94,47,141
9,Taxi service,9,4,13
10,Scenic and sightseeing transportation services,31,19,50
11,Automotive equipment rental and leasing,96,92,188
12,Automotive repair services,49,14,63
13,Parking lots and garages,22,6,28
14,Toll highways,0,0,0
15,Travel arrangement and reservation services,319,298,617
16,Motion pictures and performing arts,21,11,32
17,Spectator sports,53,48,101
18,Participant sports,252,230,482
19,Gambling,145,62,207
20,All other recreation and entertainment,59,12,71
21,Petroleum refineries,2,3,5
22,Industries producing nondurable PCE commoditie...,130,189,319
23,Wholesale trade and transportation services,178,146,324
24,Gasoline service stations,225,53,278
25,"Retail trade services, excluding gasoline serv...",347,68,415
26,All other industries,97,75,172